version: '3.1'

services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./postgres-data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: contacts
  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "rabbit1"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
    - "15672:15672"
    - "5672:5672"
  publisher:
    build: ./pub
    restart: always
    environment:
      RABBIT_HOST: rabbitmq
    depends_on:
    - rabbitmq
  subscriber:
    build: ./sub
    restart: always
    environment:
      RABBIT_HOST: rabbitmq
      DB_HOST: db
    depends_on:
      - db
      - rabbitmq





